### ISSUE TITLE
FIX BUG: Toast says "Cow Bought" even when no cow was bought

### ISSUE THREAD

**Issue by josiahnross** [ucsb-cs156-f22/f22-5pm-happycows#24]
# Overview
When buying cows, if you run out of money, the app doesn't let you continue to buy cows. However, the toast message that pops up says "Cow Bought" even if you didn't just buy a cow.

Perhaps the toast should NOT pop up when you successfully buy a cow (since you already see the number of cows go up, and your money go down), but should ONLY pop up when you are out of money and try to buy a cow.. and in that case, the message should indicate that.

# Steps to reproduce

1. Join a commons
2. Try to buy cows until you run out of money. See toasts that say "Cow Bought"
3. Try to buy another cow

- Expected: a toast that says something like: "You can't buy a cow because you don't have enough money"
- Observed: a toast that says "Cow Bought"

![Image](https://user-images.githubusercontent.com/1119017/203444338-f29c6288-aa5e-4715-aca3-0bbecdb75ac5.gif)

**Comment by Gopu2001** [comment]
This was completed by #35
